### ISSUE TITLE
Define: Architecture Characteristic / -Ility / Cross-Functional Requirement

### ISSUE THREAD

**Issue by yt-ms** [finos/devops-automation#128]
## Architecture as Code: Glossary Definition
Please see [Architecture as Code: Glossary Definition](https://github.com/finos/devops-automation/issues/121) for details on how to help with this definition.

### Title
Architecture Characteristic / -Ility / Cross-Functional Requirement

### Definition
A requirement that specifies criteria that can be used to judge the operation of a system, rather than specific behaviours.  [(1)](https://en.wikipedia.org/wiki/Non-functional_requirement)

**Comment by rocketstack-matt** [comment]
How about an extension to . . . "A requirement that specifies criteria that can be used to judge the operation of a system, rather than specific behaviours. **Whilst a functional requirement describes what a system should do, an architecture characteritic describes how a system should behave whilst doing it.**"

Would it also be worth capturing the more common characteristic we would want our solutions to support? Whilst we can list out pretty much any word that can end with 'ility' I tend to think of the more powerful / useful ones as:

- Maintainability (how easy it is to understand and support a system, including how testable the system is)
- Extendability (how easy it is to extend the functional capabilities of a system)
- Availability / Reliability (what level of uptime does the system support, how fault tolerant / self-healing is the system)
- Scalability (how easily can we increase the number of users / processes the system supports)
- Performance (how the system response time is impacted by increased usage)
