### ISSUE TITLE
DevOps Automation SIG Meeting - Jan 18, 2024

### ISSUE THREAD

**Issue by ashukla13** [finos/devops-automation#172]
## Date

Thursday, Jan 18 2024 - 12pm ET; 5pm UK

## Untracked attendees

| Name | Firm | Comment |
| :--- | :--- | :------ |

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda

- [x] Convene, roll call, welcome new people
- [ ] [Approve previous meeting minutes](https://github.com/finos/devops-automation/issues/153)
- [ ]  Working Group updates
    - [x] [Architecture as Code ](https://devops.finos.org/docs/working-groups/aasc)- @rocketstack-matt / @yt-ms 
    - [x] [Backstage ](https://devops.finos.org/docs/working-groups/backstage/)- @cnygardtw
    - [ ] [OSS Supply Chain Risk Management ](https://devops.finos.org/docs/working-groups/osssc)- @johnmark   
    - [ ] [Automated Change Deployment](https://devops.finos.org/docs/working-groups/acm) - @rvema
- [ ] Topics to cover in the SIG in 2024
    - [ ] AI Code Assistants
    - [ ] Other Topics of Interest
- [ ] _Add Items Here_
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made

- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items

- [ ] Action 1
- [ ] Action 2
- [ ] ...

### Zoom info

**Join Zoom Meeting**
- https://zoom.us/j/94904595244
- Meeting ID: 949 0459 5244
- Passcode: 545224
- Find your local number: https://zoom.us/u/aesEqmNODb

**Github Repo:** https://github.com/finos/devops-automation/

**Project Board:** https://github.com/orgs/finos/projects/33

**Mailing List:** Email devops-mutualization+subscribe@finos.org to subscribe to our mailing list

**Comment by robmoffat** [comment]
Rob / FINOS 🛩️

**Comment by johnmark** [comment]
JMW / Fannie Mae

**Comment by robmoffat** [comment]
Hi JMW, Think you wanted #173

**Comment by rocketstack-matt** [comment]
Matthew Bain | Morgan Stanley

**Comment by mcleo-d** [comment]
James McLeod / NatWest Group

**Comment by karlmoll** [comment]
Karl Moll / FINOS

**Comment by rocketstack-matt** [comment]
**Meeting convened** at 17:10 GMT

@karlmoll read the **Meeting Notices**

Prior meeting minutes were not reviewed due to lack of attendees.

**Working Group Updates**
- Architecture as Code: @rocketstack-matt 
  - build out of docs for the CALM manifest has begun, currently hosted on GH Pages.
  - @karlmoll keen to look at how AasC could help drive data capture for Sustainability initiatives. More to come based on FINOS priorities.
- Backstage: @karlmoll 
  - Discussions under way to look at a live hosted instance under FINOS with a view to provide a joined up experience across FINOS projects.
  - Cristophe Fargette will be joining the 2/19 call, 
- Updates for OSSSCRM / ACD not available.

**Additional Discussion**
- Natwest OSPO looking at how to engage with the DevOps Automation working groups, more to come.
- @mcleo-d highlighted this discussion on use of GitLab - https://github.com/finos/community/issues/301
  - Potential issues of bifurcation of projects communities, but is this outweighed by the likely enlarged engagement from GitLab focused orgs.
  - Would potential issues be at least lessened through syncing of projects between GH/GL enabling folks to discover projects, but with the 'primary' source being the only method to contribute.
